version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map container port to host port
    volumes:
      - .:/app       # Mount host directory to container directory
